// export const CHANGE_CHECK_TRAILER1_STATUS = 'CHANGE_CHECK_TRAILER1_STATUS';
export const ADD_MOVIE_TO_FAVORITE = 'ADD_MOVIE_TO_FAVORITE';
export const REMOVE_MOVIE_TO_FAVORITE = 'REMOVE_MOVIE_TO_FAVORITE';
export const ADD_USER_DETAIL = 'ADD_USER_DETAIL';
export const REMOVE_USER_DETAIL = 'REMOVE_USER_DETAIL';
